### ISSUE TITLE
Global symbol "@cP" requires explicit package name

### ISSUE THREAD

**Issue by Azraelir** [webstandardcss/letsencrypt-cpanel#7]
Global symbol "@cP" requires explicit package name at /root/installssl.pl line 11.
Execution of /root/installssl.pl aborted due to compilation errors.

how to solve this?

**Comment by webstandardcss** [comment]
This is my line 11

my $auth = "Basic " . MIME::Base64::encode( $user . ":" . $pass );

What is your line 11

I do not see the letters cP

also I checked the source of that file and do not find cP anywhere in there.  

I only wrote the bash wrapper and did not write the perl script.

Matthew at cPanel wrote the perl script https://forums.cpanel.net/members/cpmatthewv.535861/

He posted it here

https://forums.cpanel.net/threads/how-to-installing-ssl-from-lets-encrypt.513621/

I hope this helps

Trey
